/**
 * Localised strings for the UI chrome (everything outside the workspace body
 * that still needs translation: settings, waybar, hero actions, player, …).
 *
 * The workspace body takes its own content from `PortfolioContent` (see
 * portfolio.ts); this map covers the surrounding shell chrome. Keys must stay
 * in sync between both languages.
 */
export const UI_STRINGS = {
  en: {
    // Settings widget
    settingsTitle: 'settings',
    performanceLabel: 'Performance mode',
    performanceToggle: 'Reduce heavy motion & effects',
    performanceHint:
      'When on, glassmorphism blur and the decorative CAVA visualizer are enabled.',
    themeLabel: 'Theme',
    themeHint: 'Colours are extracted from the wallpaper (ColorThief).',
    languageLabel: 'Language',
    languageHint: 'Switch between English and Ukrainian.',
    languageEnglish: 'English',
    languageUkrainian: 'Українська',

    // Sidebar / player
    playerTitle: 'music',
    playerPlaying: 'playing',
    playerPaused: 'paused',
    playerArtists: 'Suno AI',
    playerSuno: 'All tracks generated by Suno AI',
    playerEmpty: 'No tracks available',

    // CAVA
    cavaLabel: 'Decorative audio visualizer',
    cavaActive: 'visualizing',
    cavaInactive: 'idle — start music & enable performance',

    // Hero actions
    hireMe: 'Hire Me',
    downloadCv: 'Download CV',
    heroPhilosophyTitle: 'The Philosophy',
    heroPhilosophyCopy:
      'Minimalism is not the absence of features, but the presence of focus. I build systems that feel like an extension of intent.',
    heroStackTitle: 'The Stack',
    heroStackCopy:
      "Deeply rooted in Python, distributed services, and the modern web's ability to deliver native-feel products with clean, measurable performance.",

    // Shortcuts
    shortcutsTitle: 'shortcuts',
    shortcutsNav: 'Navigation',
    shortcutsUtility: 'Utilities',

    // Workspaces
    wsAbout: 'About',
    wsExperience: 'Experience',
    wsSkills: 'Skills',
    wsProjects: 'Projects',
    wsEducation: 'Education',
    wsContact: 'Contact',
    // Misc
    workspaceActive: 'active',
    closeWindow: 'Close window',
    ariaWorkspace: 'workspace',
  },
  uk: {
    // Settings widget
    settingsTitle: 'налаштування',
    performanceLabel: 'Режим продуктивності',
    performanceToggle: 'Зменшити важку анімацію та ефекти',
    performanceHint:
      'Коли увімкнено, активується ефект розмиття (glassmorphism) та декоративний візуалізатор CAVA.',
    themeLabel: 'Тема',
    themeHint: 'Кольори витягуються з шпалер (ColorThief).',
    languageLabel: 'Мова',
    languageHint: 'Перемикання між англійською та українською.',
    languageEnglish: 'English',
    languageUkrainian: 'Українська',

    // Sidebar / player
    playerTitle: 'музика',
    playerPlaying: 'грає',
    playerPaused: 'пауза',
    playerArtists: 'Suno AI',
    playerSuno: 'Уся музика згенерована Suno AI',
    playerEmpty: 'Немає доступних треків',

    // CAVA
    cavaLabel: 'Декоративний аудіовізуалізатор',
    cavaActive: 'візуалізація',
    cavaInactive: 'очікування — увімкніть музику та продуктивність',

    // Hero actions
    hireMe: 'Найняти мене',
    downloadCv: 'Завантажити резюме',
    heroPhilosophyTitle: 'Філософія',
    heroPhilosophyCopy:
      'Мінімалізм — це не відсутність функцій, а наявність фокусу. Я будую системи, що відчуваються як продовження наміру.',
    heroStackTitle: 'Стек',
    heroStackCopy:
      'Глибоко вкорінений у Python, розподілених сервісах та здатності сучасного вебу доставляти продукти з відчуттям нативного вигляду, чистої та вимірюваної продуктивності.',

    // Shortcuts
    shortcutsTitle: 'короткі клавіші',
    shortcutsNav: 'Навігація',
    shortcutsUtility: 'Утиліти',

    // Workspaces
    wsAbout: 'Про мене',
    wsExperience: 'Досвід',
    wsSkills: 'Навички',
    wsProjects: 'Проєкти',
    wsEducation: 'Освіта',
    wsContact: 'Контакти',

    // Misc
    workspaceActive: 'активна',
    closeWindow: 'Закрити вікно',
    ariaWorkspace: 'робочий стіл',
  },
} as const;

export type UiStrings = (typeof UI_STRINGS)['en'];
